cashonad_admin_homepage:
    pattern:  /
    defaults: { _controller: CashonadAdminBundle:Admin:index }
    requirements:
        _method:  GET

board:
    pattern:  /board
    defaults: { _controller: CashonadAdminBundle:Admin:board }
    requirements:

chart:
    pattern:  /chart
    defaults: { _controller: CashonadAdminBundle:Admin:chart }
    requirements:

image:
    pattern:  /image
    defaults: { _controller: CashonadAdminBundle:Admin:image }
    requirements:

profile:
        pattern: /profile
        defaults: { _controller: CashonadAdminBundle:Admin:profile}
        requirements:
news:
        pattern: /list
        defaults: { _controller: CashonadAdminBundle:News:news}
        requirements:


add:
        pattern: /add
        defaults: { _controller: CashonadAdminBundle:News:add}
        requirements:

delete:
    pattern:  /{id}/delete/
    defaults: { _controller: CashonadAdminBundle:News:delete }
    requirements:
        id:  \d+

edit:
    pattern:  /{id}/edit/
    defaults: { _controller: CashonadAdminBundle:News:edit }
    requirements:
        id:  \d+







