parameters:
#    cashonad_admin.example.class: Cashonad\AdminBundle\Example

services:
#    cashonad_admin.example:
#        class: %cashonad_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
