cashonad_profile_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: CashonadProfileBundle:Default:index }


cashonad_dashboard:
    pattern:  /dashboard
    defaults: { _controller: CashonadProfileBundle:Dashboard:index }

cashonad_resetting:
    pattern:  /request
    defaults: { _controller: CashonadProfileBundle:Resetting:request }

