parameters:
#    cashonad_main.example.class: Cashonad\MainBundle\Example

services:
#    cashonad_main.example:
#        class: %cashonad_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
